-- MySQL Script generated by MySQL Workbench
-- Wed Apr 24 09:59:45 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema siopm_bombeiro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema siopm_bombeiro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `siopm_bombeiro` DEFAULT CHARACTER SET utf8 ;
USE `siopm_bombeiro` ;

-- -----------------------------------------------------
-- Table `siopm_bombeiro`.`chamados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siopm_bombeiro`.`chamados` ;

CREATE TABLE IF NOT EXISTS `siopm_bombeiro`.`chamados` (
  `nroOcorrencia` INT(11) NOT NULL AUTO_INCREMENT,
  `data_ocorrencia` DATETIME NULL DEFAULT NULL,
  `centro_atendimento` INT(11) NULL DEFAULT NULL,
  `situacao_ocorrencia` VARCHAR(45) NULL DEFAULT NULL,
  `data_geracao` DATETIME NULL DEFAULT NULL,
  `unidade` VARCHAR(45) NULL DEFAULT NULL,
  `prioridade` VARCHAR(45) NULL DEFAULT NULL,
  `latitude` VARCHAR(45) NULL DEFAULT NULL,
  `longitude` VARCHAR(45) NULL DEFAULT NULL,
  `data_chamada` DATE NULL DEFAULT NULL,
  `hora_chamada` TIME NULL DEFAULT NULL,
  `telefone_solicitante` VARCHAR(45) NULL DEFAULT NULL,
  `nome_solicitante` VARCHAR(100) NULL DEFAULT NULL,
  `cpf_solicitante` VARCHAR(45) NULL DEFAULT NULL,
  `prefixo_viatura` VARCHAR(45) NULL DEFAULT NULL,
  `natureza` VARCHAR(45) NULL DEFAULT NULL,
  `descricao` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`nroOcorrencia`))
ENGINE = MyISAM
AUTO_INCREMENT = 93
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `siopm_bombeiro`.`equipamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siopm_bombeiro`.`equipamento` ;

CREATE TABLE IF NOT EXISTS `siopm_bombeiro`.`equipamento` (
  `eqt_id` INT(11) NOT NULL AUTO_INCREMENT,
  `ptt_id` INT(11) NOT NULL,
  `nome` VARCHAR(200) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `imagem_url` TEXT NULL DEFAULT NULL,
  `preco` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`eqt_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `siopm_bombeiro`.`patente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siopm_bombeiro`.`patente` ;

CREATE TABLE IF NOT EXISTS `siopm_bombeiro`.`patente` (
  `ptt_id` INT(11) NOT NULL AUTO_INCREMENT,
  `classe` VARCHAR(200) NULL DEFAULT NULL,
  `pontuacao_minima` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`ptt_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `siopm_bombeiro`.`pontocorrencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siopm_bombeiro`.`pontocorrencia` ;

CREATE TABLE IF NOT EXISTS `siopm_bombeiro`.`pontocorrencia` (
  `pct_id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` TEXT NULL DEFAULT NULL,
  `natureza` VARCHAR(200) NULL DEFAULT NULL,
  `sigla` VARCHAR(45) NULL DEFAULT NULL,
  `pontuacao` TINYINT(4) NULL DEFAULT NULL,
  `relacao_ponto_nivel` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`pct_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `siopm_bombeiro`.`usuariooauth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siopm_bombeiro`.`usuariooauth` ;

CREATE TABLE IF NOT EXISTS `siopm_bombeiro`.`usuariooauth` (
  `uth_id` INT(11) NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NULL DEFAULT NULL,
  `hash` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`uth_id`))
ENGINE = MyISAM
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `siopm_bombeiro`.`voluntariojogo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siopm_bombeiro`.`voluntariojogo` ;

CREATE TABLE IF NOT EXISTS `siopm_bombeiro`.`voluntariojogo` (
  `vasb_id` INT(11) NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `nickname` VARCHAR(200) NULL DEFAULT NULL,
  `avatar_url` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`vasb_id`),
  UNIQUE INDEX `idxUUID` (`uuid` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `siopm_bombeiro`.`voluntarioponto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siopm_bombeiro`.`voluntarioponto` ;

CREATE TABLE IF NOT EXISTS `siopm_bombeiro`.`voluntarioponto` (
  `vpt_id` INT(11) NOT NULL AUTO_INCREMENT,
  `vasb_id` INT(11) NULL DEFAULT NULL,
  `pct_id` INT(11) NULL DEFAULT NULL,
  `quando` DATETIME NULL DEFAULT NULL,
  `inserido_por` VARCHAR(200) NULL DEFAULT NULL,
  PRIMARY KEY (`vpt_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `siopm_bombeiro`.`voluntariosaldo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siopm_bombeiro`.`voluntariosaldo` ;

CREATE TABLE IF NOT EXISTS `siopm_bombeiro`.`voluntariosaldo` (
  `vsd_id` INT(11) NOT NULL AUTO_INCREMENT,
  `vasb_id` INT(11) NOT NULL,
  `valor` INT(11) NOT NULL,
  `entrada_saida` TINYINT(1) NOT NULL,
  `pct_id` INT(11) NULL DEFAULT NULL,
  `eqt_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`vsd_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `siopm_bombeiro`.`voluntatarioequipamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `siopm_bombeiro`.`voluntatarioequipamento` ;

CREATE TABLE IF NOT EXISTS `siopm_bombeiro`.`voluntatarioequipamento` (
  `veq_id` INT(11) NOT NULL AUTO_INCREMENT,
  `vasb_id` INT(11) NULL DEFAULT NULL,
  `eqt_id` INT(11) NULL DEFAULT NULL,
  `comprado_quando` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`veq_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
